global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Cats.BussinesObjects.Entities;
global using Cats.BussinesObjects.Interfaces;
global using Cats.BussinesObjects.ValueObjects;
global using System.Net.Http.Json;
